name=BLE
version=1.0
author=(Original) Nordic Semiconductor ASA :: Ported to STM32+AVR by In-Circuit GmbH.
email=
sentence=BLE library for radino nRF8001 and radino32 nRF8001
paragraph=
url=www.in-circuit.de
architectures=avr,STM32L1
maintainer=
category=Communication
