name=IC_ESP
version=1.0
author=In-Circuit GmbH.
email=
sentence=Library for ESP on radino WiFi and radino32 WiFi
paragraph=
url=www.in-circuit.de
architectures=avr,STM32L1
maintainer=
category=Communication
