name=IC_SX1272
version=1.0
author=(Original) SEMTECH S.A. :: modified by In-Circuit GmbH.
email=
sentence=Library for radino32 SX1272
paragraph=
url=www.in-circuit.de
architectures=STM32L1
maintainer=
category=Communication
