name=IC_CC1101
version=1.0
author=In-Circuit GmbH.
email=
sentence=CC1101 library for radino CC1101 and radino32 CC1101
paragraph=
url=www.in-circuit.de
architectures=avr,STM32L1
maintainer=
category=Communication
