name=radino32_UART
version=1.0
author=In-Circuit GmbH.
email=
sentence=ESP-UART library for radino32 WiFi
paragraph=
url=www.in-circuit.de
architectures=STM32L1
maintainer=
category=Communication
