name=SoftwareSerial
version=1.0
author=Arduino modified for radino32
maintainer=Arduino <info@arduino.cc>
sentence=Enables serial communication on digital pins. For all Arduino boards, BUT Arduino DUE.
paragraph=
url=http://arduino.cc/en/Reference/SoftwareSerial
architectures=avr,STM32L1
category=Communication
